var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "               v                                                                ",
   "                                                                  xxx           ",
   "                                                                 xx!xx          ",
   "                                                                 x!!!x          ",
   "                         o o                                     xx!xx          ",
   "                                    o o                           xvx           ",
   "                        xxxxx                                                   ",
   "                                   xxxxx                                        ",
   "                                                                        xxxxxxx ",
   "  xx                                      o o           s               x    xx ",
   "  x            o                                                        x    xx ",
   "  x                                      xxxxx                          x oo xx ",
   "  x          xx xx                                                           xx ",
   "  x  @                                                           xxxxx       xx ",
   "  xxxxxxxxx         xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxx ",
   "          x!!!!!!!!!x         x   x                  x     x                    ",
   "          xxxxxxxxxxx         x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  [" v     v                                                                                 ",
   "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
   "         x                                         x        o                            ",
   "         x                                         xxxxx                                 ",
   " v  @  v x        xxxxxxxxxxxxxxxxxxxxxx      o         xxxxxxxx!xxxxxx!xxxxx!xxxxx      ",
   "         x                              x                       x      x     x           ",
   "         x    s                          xxxxx                                         xx",
   "         x                                    xx                                         ",
   "         x  xxxxx                               xxxxxxxxxxxxx                            ",
   "         x                                                                         xx    ",
   "    o    x       xxxxxxx         t                                         o             ",
   "         x      x!!!!!!!x    xx                                                          ",
   " v  o  v x      x!!!!!!!x           x                           xx     xxxxxxxx          ",
   "         x       x!!!!!x                xxxn                          xx!!!!!!xx         ",
   "         x         vvv                                                  xxvvxx           ",
   "         x                                             o                                 ",
   "         x                                                                         xx    ",
   "         x                                                                               ",
   "         x                                                   t                          x",
   "         x                                       t   xxxxx                               ",
   "    o    x                                xxxxx                                          ",
   "                                                                xxxxx                 xxx",
   "                                xxxxx                                             s      ",
   "                                                                        xxxxxx           ",
   "                                                                                  x      ",
   "             xxxxx!!!!!xxxxx                                                             ",
   "             x   xxxxxxx   x!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!!!!!!",
   "    x        x             x!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!!!x!!!!!!!!!!x!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                         ",
   "                                                                                         "],
  ["!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                       ",
   "!!!!!!!!!!!!!!v!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!v!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!v!!!!!!!!v",
   "xvvxvvxxxxvx x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxx xxxxxxxx ",
   "        x        xx                                                                                           ",
   "        x       xxxx                                                                                          ",
   "        x      xx  xx                                                                                         ",
   "        x      xxxxxx                                                                                         ",
   "        x      x    x                                                                                         ",
   "        x!!!!!!x    x                                                                                         ",
   "        x!!!!!!x    x   o o     o     o     o      o     o       o    t   xxx     x     xx xx   xxx      x    ",
   "        x!!!!!!x    x                                                                                         ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         ",
   "                                                                                                             x",
   "                                                                                                              ",
   "                                                                                                         x    ",
   "                                                                                                  x           ",
   "   s                                                                                        x                 ",
   "                                            o                       o                x                        ",
   "   x                                             t           t                                                ",
   "x!!!!!xx                             x    xxxxx       xxxxx       xxxxx      xxx                              ",
   "x!!!!!!x                        x         x!!!x       x!!!x       x!!!x                 x!!x                  ",
   "x!!!!!!x                  x                xvx         xvx         xvx                  x!!x                  ",
   "x!!!!!!xx                                                                               xxxx                  ",
   "xxxxxvxx            x                                                                                         ",
   "       x                                                                                                      ",
   "  @    x      x                                                                                               ",
   "       x                                                                                             o        ",
   "       xx                                                                                     t               ",
   "       x                                                                                            xxx      x",
   "       x                                                                                                      ",
   "       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
   "                                                                                                              ",
   "                                                                                                         x    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                          o                                                                                  x",
   "                                                                                o     o                       ",
   "                          x                     o                                                      xxx    ",
   "                                                                       o        x     x                       ",
   "                     x                          x                            x                       x        ",
   "  xx              t            x                                t      x                                      ",
   "              x                           x          x                                   x       x            ",
   "       x                            x                       x       x                        x                ",
   "                                                                                                              ",
   "x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!x!",
   "                                                                                                              "],
  ["                                                                                                              ",
   "vvvvvvvvv           vv     @    vv          vvv vvv                vv        vv               vvvv   vvvvvvvvv",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "         xx       xx  xxxxxxxxxx  x        x   x   x              x  xxxxxxxx  xxx           x    xxx         ",
   "          x       x   x        x  x        x       x              x     xx     x  x          x    xxx         ",
   "          x       x   x        x  x        x       x      xx      x     xx     x   x    x    x    xxx         ",
   "           x     x    x        x  x   xx   x       x              x     xx     x    x        x    xxx         ",
   "            x   x     x        x  x        x       x              x     xx     x     x       x    xxx         ",
   "             xxx      x        x  x        x       x              x     xx     x      x      x    xxx         ",
   "              x       x        x  x       xx       x      xx      x     xx     x       x     x    xxx         ",
   "              x       x        x  x        x       x     x  x     x     xx     x        x    x    xxx         ",
   "              x       x        x  x        x       x    x    x    x     xx     x         x   x                ",
   "              x       x        x  x        x       x   x      x   x     xx     x          x  x    xxx         ",
   "              x       xxxxxxxxxx  xxxxxxxxxx       xxxxx      xxxxx  xxxxxxxx  x           xxx    xxx         ",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
